repos:
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
    exclude: code_samples/(.+)\.py
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort (python)
